title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
color_scheme: dark
enable_theme_toggle: true
favicon_ico: "/assets/img/logo/main.ico"
url: https://just-the-docs.github.io
sass:
  style: compressed


aux_links:
  My repository: https://github.com/Anen135/my_test_repo.git

defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      permalink: "/:basename"
